services:
  my-mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: my_mssql
    ports:
      - "12345:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Ver7CompleXPW"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-No", "-U", "sa", "-P", "Ver7CompleXPW", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: unless-stopped # 若容器異常停止，會自動重啟（除非手動停止）

  my-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: my_elasticsearch
    ports:
      - "19200:9200"  # 對外暴露 Elasticsearch 的 HTTP REST API 埠（用於查詢與索引）
      - "19300:9300"  # 對外暴露 Elasticsearch 的內部節點通訊埠（用於集群節點間溝通）
    environment:
      discovery.type: single-node  # 設定為單節點模式，避免啟動時等待其他節點
      xpack.security.enabled: "false"  # 關閉 X-Pack 安全機制（如帳號密碼驗證），方便開發測試
    mem_limit: 2g  # 限制容器最大記憶體使用量為 2GB，避免 OOM
    restart: unless-stopped  # 若容器異常停止，會自動重啟（除非手動停止）

  my-kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0 # Kibana UI，官方推薦的 Elasticsearch 管理介面
    container_name: my_kibana
    ports:
      - "15601:5601"  # 對外暴露 Kibana 的 Web 介面 (http://localhost:15601)
    environment:
      ELASTICSEARCH_HOSTS: '["http://my_elasticsearch:9200"]' # 設定要連接的 Elasticsearch 服務
    depends_on:
      - my-elasticsearch # 啟動順序依賴 elasticsearch
    restart: unless-stopped # 若容器異常停止，會自動重啟（除非手動停止）

  # ------------------------------------------------------------------------------------------------------------------------------
  # mssql-setup: 一次性的資料庫初始化服務
  # 這個服務的唯一目的，是在 my-mssql 服務準備就緒後，自動執行 SQL 腳本 (00_手動執行_建立DB.sql) 來建立資料庫 ACTION_LOG_DB
  # 執行完腳本後，容器會持續運行以便進行調試，但它只會執行一次初始化任務
  # ------------------------------------------------------------------------------------------------------------------------------
  mssql-setup:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_setup
    labels:
      org.springframework.boot.ignore: "true" # Spring Boot 不會嘗試管理這個容器
    depends_on:
      my-mssql:
        # 等待 my-mssql 服務的 healthcheck 狀態變為 'healthy' 後，才開始執行此服務
        condition: service_healthy
    volumes:
      # 將本地的 SQL 腳本資料夾掛載到容器的 /sql-scripts 路徑下
      - ./src/main/resources/init_db:/sql-scripts
    # command 是此容器的主程序。它會先執行初始化腳本，然後進入無限睡眠 (sleep infinity)
    # 這可以讓容器保持運行狀態，方便開發者進入容器 (docker exec) 檢查腳本執行結果或進行調試
    # 因為沒有設定 restart 策略，此容器在手動停止後不會自動重啟
    command: >
      sh -c "
      /opt/mssql-tools18/bin/sqlcmd -S my-mssql -No -U sa -P 'Ver7CompleXPW' -d master -i /sql-scripts/00_手動執行_建立DB.sql && sleep infinity
      "