spring:
  application:
    name: SpringBoot-Elasticsearch

  # SQL Server 配置
  datasource:
    url: jdbc:sqlserver://localhost:12345;databaseName=ACTION_LOG_DB;encrypt=true;trustServerCertificate=true
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:Ver7CompleXPW}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # HikariCP 連接池配置
    hikari:
      maximum-pool-size: 20 # 最大連接數
      minimum-idle: 5 # 最小空閒連接數
      idle-timeout: 300000 # 空閒連接超時時間（毫秒）
      connection-timeout: 20000 # 連接超時時間（毫秒）

  # 初始化 SQL 腳本
  sql:
    init:
      mode: always
      encoding: UTF-8
      continue-on-error: false
      schema-locations: classpath:init_db/01_schema.sql
      data-locations: classpath:init_db/02_data.sql
      username: ${DB_USERNAME:sa}
      password: ${DB_PASSWORD:Ver7CompleXPW}

  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # 使用標準命名策略，避免自動轉換表名和列名
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    defer-datasource-initialization: false  # 延遲資料庫初始化，確保在 [初始化 SQL 腳本] 後執行

  # Elasticsearch 配置
  elasticsearch:
    uris: http://localhost:19200  # Elasticsearch 節點的 URI，這是最重要的部分
    username: ${ELASTICSEARCH_USERNAME:}
    password: ${ELASTICSEARCH_PASSWORD:}
    index:
      name: action_log_index # 指定索引名稱(must be lowercase)
      shards: 1
      replicas: 1

# 日誌配置
logging:
  charset:
    console: utf-8
  level:
    # com.example.elasticsearch: DEBUG
    org.springframework.data: INFO
    # org.springframework.boot.autoconfigure.sql.init: DEBUG
    # org.springframework.jdbc.datasource.init: DEBUG

# 同步配置
sync:
  enabled: true
  full-sync-on-startup: true
  incremental-interval-seconds: 30
  batch-size: 1000